# Generated by Django 4.1.3 on 2026-01-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_from_email', models.EmailField(default='haripriyamax1427@gmail.com', help_text='Default from email address', max_length=255)),
                ('email_timeout', models.IntegerField(default=30, help_text='Email timeout in seconds')),
                ('use_django_backend', models.BooleanField(default=True, help_text='Use Django email backend as fallback')),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', help_text='SMTP server hostname', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP server port (587 for TLS, 465 for SSL)')),
                ('smtp_username', models.CharField(help_text='SMTP username/email', max_length=255)),
                ('smtp_password', models.CharField(help_text='SMTP password', max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('smtp_use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption')),
                ('is_active', models.BooleanField(default=True, help_text='Use this configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP Configuration',
                'verbose_name_plural': 'SMTP Configurations',
            },
        ),
    ]
