# Generated by Django 4.1.3 on 2026-01-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpconfiguration',
            name='smtp_host',
            field=models.CharField(help_text='SMTP server hostname', max_length=255),
        ),
        migrations.AlterField(
            model_name='smtpconfiguration',
            name='smtp_port',
            field=models.IntegerField(help_text='SMTP server port (587 for TLS, 465 for SSL)'),
        ),
    ]
