# Generated by Django 4.1.3 on 2026-01-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_smtpconfiguration_smtp_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpconfiguration',
            name='smtp_host',
            field=models.CharField(default='smtp.gmail.com', help_text='SMTP server hostname', max_length=255),
        ),
        migrations.AlterField(
            model_name='smtpconfiguration',
            name='smtp_port',
            field=models.IntegerField(default=587, help_text='SMTP server port (587 for TLS, 465 for SSL)'),
        ),
    ]
